### PR TITLE
173 Custom Fields when modifying organisation

### LINKED ISSUE #173: Accidental(?) Custom Fields when modifying organisation
### What happened?

I went to "Manage" the Fjelltopp organisation (https://zarr.fjelltopp.org/organization/edit/fjelltopp) and I saw this:
image

These custom fields probably need to be removed? I am not sure where they come from?

### Regression Test

- [ ] Of course it is!

### Version

Prod deployed

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by A-Souhei**
## Description

Removes custom fields from organization's new and edit pages.

image

Closes https://github.com/fjelltopp/zarr-ckan/issues/173
## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Review by ChasNelson1990 — COMMENTED** [review]
Where do those fields originally come from?

**Comment by A-Souhei** [comment]
@ChasNelson1990 , the fields are in the block in zarr-ckan/ckan/ckan/templates/organization/snippets/organization_form.html:

```
  {% block custom_fields %}
    {% snippet 'snippets/custom_form_fields.html', extras=data.extras, errors=errors, limit=3 %}
  {% endblock %}
```

**Comment by ChasNelson1990** [comment]
@A-Souhei - but that block is only handling formatting of the custom fields why do we have these fields in the data dictionary at all?

**Comment by A-Souhei** [comment]
I will look more at it tomorrow.

**Comment by A-Souhei** [comment]
@ChasNelson1990 , from snippets/custom_form_fields.html:

```
  {# Add a max of 3 empty columns #}
  {% set total_extras = extras|count %}
  {% set empty_extras = (limit or 3) - total_extras %}
  {% if empty_extras <= 0 %}{% set empty_extras = 1 %}{% endif %}
```

This chunk will make it that even if we set limit to 0 in previous comment code, it will add 3 customs fields by default.

Should I update this template instead?

I tried with a vanilla ckan docker compose stack :

image

**Comment by ChasNelson1990** [comment]
@A-Souhei do we know why this was added? Or when, is it recent? Is there a good reason?

**Comment by A-Souhei** [comment]
Some interesting discussions about it :
https://github.com/ckan/ckan/issues/6037

**Review by ChasNelson1990 — APPROVED** [review]
Let's get this merged

**Pull request merged**
