### PR TITLE
Add Organizations to menu bar

### LINKED ISSUE #164: Add Organizations to menu bar
### Problem

The client wants to be able to quickly search the repository by which organisation uploaded the data.

### Solution

Add Organizations to menu bar.

### Considerd Alternatives

_No response_

### PR DESCRIPTION
**Pull request by A-Souhei**
## Description

Adds facet organizations to left menu bar and removed program areas.
Also added groups as 'Topics'

image

Closes https://github.com/fjelltopp/zarr-ckan/issues/164

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
This is a good change but not actually what I meant. Can we add Organizations here:
image

**Comment by A-Souhei** [comment]
Added organizations to top menu and renamed Find data to Data:

image
image

**Comment by A-Souhei** [comment]
> This is a good change but not actually what I meant. Can we add Organizations here: image

Updated top nav, renamed 'Find data' to 'Data':

image

**Review by ChasNelson1990 — APPROVED** [review]
LGTM

**Pull request merged**
