### PR TITLE
175 - Use official zambia flag colours

### LINKED ISSUE #175: Use official Zambia flag colours
### Problem

We have been asked to use the official flag colours for the green, black, red and orange.

### Solution

Please use the exact colours from the flag - we will then share a before and after screenshot with them.

### Considerd Alternatives

_No response_

### PR DESCRIPTION
**Pull request by A-Souhei**
## Description
Closes https://github.com/fjelltopp/zarr-ckan/issues/175

My attempt  to use the palette from Zambia flag.

I took the palette from wiki:
image

Screenshots:

Footer
image

masthead and promoted :
image

main hero:
image

package:
image

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Okay. It looks has horrible as I warned them it would! I might try and rope Lewis in for a bit of advise here.

**Comment by ChasNelson1990** [comment]
Let's pair on this when you are next working.

**Comment by A-Souhei** [comment]
I close this one.

**Comment by A-Souhei** [comment]
I reopen and set to draft.

**Pull request closed without merging**
